# Generated by Django 5.2 on 2025-05-02 03:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='도시명')),
                ('slug', models.SlugField(unique=True, verbose_name='슬러그')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('order', models.IntegerField(default=0, verbose_name='정렬 순서')),
            ],
            options={
                'verbose_name': '도시',
                'verbose_name_plural': '도시',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TravelOptionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupTravel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='그룹명')),
                ('description', models.TextField(verbose_name='그룹 설명')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_groups', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='joined_groups', through='travel_input.GroupMember', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='travel_input.grouptravel')),
            ],
        ),
        migrations.AddField(
            model_name='groupmember',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_input.grouptravel'),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='일정 제목')),
                ('destination', models.CharField(max_length=200, verbose_name='여행지')),
                ('start_date', models.DateField(verbose_name='시작일')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='종료일')),
                ('budget', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='예산')),
                ('notes', models.TextField(blank=True, max_length=5000, null=True, verbose_name='메모')),
                ('num_people', models.IntegerField(default=1, verbose_name='인원수')),
                ('departure_region', models.CharField(blank=True, max_length=50, null=True, verbose_name='출발 지역')),
                ('purpose', models.CharField(blank=True, max_length=50, null=True, verbose_name='여행 목적')),
                ('season_peak', models.CharField(blank=True, max_length=50, null=True, verbose_name='성수기 여부')),
                ('pet_friendly', models.CharField(blank=True, max_length=10, null=True, verbose_name='반려동물 동반 여부')),
                ('people_composition', models.CharField(blank=True, max_length=100, null=True, verbose_name='사람 구성')),
                ('lodging_request', models.CharField(blank=True, max_length=200, null=True, verbose_name='숙소 요청사항')),
                ('comments', models.TextField(blank=True, max_length=1000, null=True, verbose_name='기타 요청사항')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '여행 일정',
                'verbose_name_plural': '여행 일정들',
                'ordering': ['-created_at', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('visit_date', models.DateField()),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='travel_input.schedule')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='travel_input.schedule')),
            ],
        ),
        migrations.CreateModel(
            name='ImportantFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor', models.CharField(choices=[('숙소', '숙소'), ('음식', '음식'), ('날씨', '날씨'), ('일정 편의성', '일정 편의성'), ('현지 문화', '현지 문화')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='important_factors', to='travel_input.schedule')),
            ],
            options={
                'verbose_name': '중요 요소',
                'verbose_name_plural': '중요 요소',
            },
        ),
        migrations.AddField(
            model_name='grouptravel',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_travels', to='travel_input.schedule'),
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='travel_input.schedule')),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transports', to='travel_input.schedule')),
            ],
            options={
                'verbose_name': '교통수단',
                'verbose_name_plural': '교통수단',
            },
        ),
        migrations.CreateModel(
            name='TravelOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='travel_input.traveloptioncategory')),
            ],
        ),
        migrations.CreateModel(
            name='TravelStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(choices=[('자연경관', '자연경관'), ('문화 체험', '문화 체험'), ('도시 탐방', '도시 탐방'), ('액티비티', '액티비티'), ('휴식', '휴식')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_styles', to='travel_input.schedule')),
            ],
            options={
                'verbose_name': '여행 스타일',
                'verbose_name_plural': '여행 스타일',
            },
        ),
        migrations.AlterUniqueTogether(
            name='groupmember',
            unique_together={('group', 'user')},
        ),
    ]
