# Generated by Django 5.2 on 2025-05-02 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_input', '0002_remove_schedule_comments_remove_schedule_num_people_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='name',
        ),
        migrations.AddField(
            model_name='participant',
            name='gender',
            field=models.CharField(choices=[('남자', '남자'), ('여자', '여자')], default='남자', max_length=10, verbose_name='성별'),
        ),
        migrations.AddField(
            model_name='participant',
            name='is_elderly',
            field=models.BooleanField(default=False, verbose_name='고령자 여부'),
        ),
        migrations.AddField(
            model_name='participant',
            name='is_family',
            field=models.BooleanField(default=False, verbose_name='가족 여부'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='age',
            field=models.IntegerField(default=20, verbose_name='나이'),
        ),
    ]
