# Generated by Django 5.2 on 2025-05-02 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_input', '0009_remove_participant_age_participant_num_people'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='age_type',
        ),
        migrations.AddField(
            model_name='participant',
            name='age_range',
            field=models.CharField(choices=[('10대', '10대'), ('20대', '20대'), ('30대', '30대'), ('40대', '40대'), ('50대', '50대'), ('60대', '60대'), ('70대', '70대'), ('80대', '80대')], default='20대', max_length=10, verbose_name='연령대'),
        ),
    ]
