# Generated by Django 5.2.1 on 2025-05-12 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_input', '0009_schedule_important_factors_schedule_travel_style'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='important_factors',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='is_favorite',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='lodging_request',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='num_people',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='people_composition',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='pet_friendly',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='purpose',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='transport',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='travel_style',
        ),
        migrations.AddField(
            model_name='schedule',
            name='participant_info',
            field=models.TextField(blank=True, default='', help_text='참가자 이름과 나이를 입력하세요 (예: 홍길동(30), 김철수(25))', null=True, verbose_name='참가자'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='place_info',
            field=models.TextField(blank=True, default='', help_text='방문할 장소와 날짜를 입력하세요 (예: 남산타워(2024-03-20), 경복궁(2024-03-21))', null=True, verbose_name='방문 장소'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='transport_info',
            field=models.TextField(blank=True, default='', help_text='교통편, 출발지, 도착지, 시간을 입력하세요 (예: KTX, 서울역, 부산역, 2024-03-20 09:00)', null=True, verbose_name='교통 정보'),
        ),
    ]
