# Generated by Django 5.1.6 on 2025-05-16 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel_input", "0013_airecommendation"),
    ]

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="지역명"
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="schedule",
            name="age_group",
            field=models.CharField(
                blank=True, default="", max_length=50, null=True, verbose_name="연령대"
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="group_type",
            field=models.CharField(
                blank=True,
                default="",
                max_length=50,
                null=True,
                verbose_name="여행 동행 형태",
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="language_support",
            field=models.BooleanField(default=False, verbose_name="언어 지원 필요"),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="meal_preference",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="음식 선호"
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="mobility_needs",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="이동 관련 요구"
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="participant_info",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="참가자"
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="place_info",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="방문 장소"
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="preferred_activities",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="선호 활동"
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="repeat_visitor",
            field=models.BooleanField(default=False, verbose_name="재방문 여부"),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="season",
            field=models.CharField(
                blank=True,
                default="",
                max_length=50,
                null=True,
                verbose_name="희망 계절",
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="transport_info",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="교통 정보"
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="travel_insurance",
            field=models.BooleanField(default=False, verbose_name="여행자 보험 가입"),
        ),
        migrations.CreateModel(
            name="Specialty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="특산물명")),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specialties",
                        to="travel_input.region",
                        verbose_name="지역",
                    ),
                ),
            ],
        ),
    ]
