# Generated by Django 5.2 on 2025-04-29 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_input', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='notes',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='메모'),
        ),
    ]
