# Generated by Django 5.2 on 2025-04-30 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_input', '0002_alter_schedule_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='도시명')),
                ('slug', models.SlugField(unique=True, verbose_name='슬러그')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('order', models.IntegerField(default=0, verbose_name='정렬 순서')),
            ],
            options={
                'verbose_name': '도시',
                'verbose_name_plural': '도시',
                'ordering': ['order', 'name'],
            },
        ),
    ]
