# Generated by Django 5.1.6 on 2025-05-01 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel_input", "0003_city"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="is_favorite",
            field=models.BooleanField(default=False, verbose_name="즐겨찾기"),
        ),
    ]
