# Generated by Django 5.1.6 on 2025-05-02 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel_input", "0007_culturecategory_schedule_lodging_request_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="num_people",
            field=models.IntegerField(default=1, verbose_name="여행 인원"),
        ),
        migrations.AddField(
            model_name="schedule",
            name="purpose",
            field=models.TextField(blank=True, verbose_name="여행 목적"),
        ),
        migrations.AddField(
            model_name="schedule",
            name="transport",
            field=models.CharField(blank=True, max_length=50, verbose_name="교통편"),
        ),
    ]
