# Generated by Django 5.2.1 on 2025-05-12 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_input', '0010_remove_schedule_important_factors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='age_group',
            field=models.CharField(blank=True, default='', help_text='예: 20대, 30대, 60대 이상 등', max_length=50, null=True, verbose_name='연령대'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='event_interest',
            field=models.BooleanField(default=False, verbose_name='현지 이벤트/축제 관심'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='group_type',
            field=models.CharField(blank=True, default='', help_text='가족, 친구, 커플, 혼자 등', max_length=50, null=True, verbose_name='여행 동행 형태'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='language_support',
            field=models.BooleanField(default=False, help_text='영어 가능 가이드 요청 등', verbose_name='언어 지원 필요'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='meal_preference',
            field=models.TextField(blank=True, default='', help_text='예: 한식, 채식, 미식 여행 등', null=True, verbose_name='음식 선호'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='mobility_needs',
            field=models.TextField(blank=True, default='', help_text='예: 휠체어 접근성, 편안한 이동 동선 등', null=True, verbose_name='이동 관련 요구'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='preferred_activities',
            field=models.TextField(blank=True, default='', help_text='예: 온천, 쇼핑, 등산, 박물관 등', null=True, verbose_name='선호 활동'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='repeat_visitor',
            field=models.BooleanField(default=False, help_text='해당 지역 방문 경험 (처음/재방문)', verbose_name='재방문 여부'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='season',
            field=models.CharField(blank=True, default='', help_text='봄, 여름, 가을, 겨울 등', max_length=50, null=True, verbose_name='희망 계절'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='travel_insurance',
            field=models.BooleanField(default=False, help_text='여행자 보험 가입 여부 또는 희망 여부', verbose_name='여행자 보험 가입'),
        ),
    ]
