# Generated by Django 5.0.2 on 2025-05-13 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_input', '0012_remove_destination_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='schedule',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.AlterUniqueTogether(
            name='groupmember',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='groupmember',
            name='group',
        ),
        migrations.RemoveField(
            model_name='groupmember',
            name='user',
        ),
        migrations.RemoveField(
            model_name='grouptravel',
            name='members',
        ),
        migrations.RemoveField(
            model_name='groupmessage',
            name='group',
        ),
        migrations.RemoveField(
            model_name='groupmessage',
            name='user',
        ),
        migrations.RemoveField(
            model_name='grouptravel',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='grouptravel',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='place',
            name='category',
        ),
        migrations.RemoveField(
            model_name='place',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='traveloption',
            name='category',
        ),
        migrations.AddField(
            model_name='schedule',
            name='travel_purpose',
            field=models.JSONField(blank=True, default=list, verbose_name='여행 목적'),
        ),
        migrations.DeleteModel(
            name='Budget',
        ),
        migrations.DeleteModel(
            name='GroupMember',
        ),
        migrations.DeleteModel(
            name='GroupMessage',
        ),
        migrations.DeleteModel(
            name='GroupTravel',
        ),
        migrations.DeleteModel(
            name='Participant',
        ),
        migrations.DeleteModel(
            name='Place',
        ),
        migrations.DeleteModel(
            name='Transport',
        ),
        migrations.DeleteModel(
            name='TravelOption',
        ),
        migrations.DeleteModel(
            name='TravelOptionCategory',
        ),
    ]
