# Generated by Django 5.2.1 on 2025-05-15 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_input', '0012_remove_destination_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='num_people',
            field=models.IntegerField(blank=True, help_text='총 여행 인원 수를 입력하세요', null=True, verbose_name='인원수'),
        ),
    ]
