# Generated by Django 5.2.1 on 2025-05-15 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_input', '0013_schedule_num_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='종료일'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_date',
            field=models.DateTimeField(verbose_name='시작일'),
        ),
    ]
