# Generated by Django 5.0.2 on 2025-05-13 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_input', '0014_city_traveloptioncategory_alter_schedule_age_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='important_factors',
            field=models.JSONField(blank=True, default=list, verbose_name='중요 요소'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='travel_style',
            field=models.JSONField(blank=True, default=list, verbose_name='여행 스타일'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='place_info',
            field=models.TextField(blank=True, default='', help_text='방문할 장소와 날짜를 입력하세요', null=True, verbose_name='방문 장소'),
        ),
    ]
