# Generated by Django 5.2.1 on 2025-05-16 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_input', '0014_alter_schedule_end_date_alter_schedule_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='num_people',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='종료일'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_date',
            field=models.DateField(verbose_name='시작일'),
        ),
    ]
