# Generated by Django 5.0.2 on 2025-05-14 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_input', '0015_schedule_important_factors_schedule_travel_style_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='favorite',
            field=models.BooleanField(default=False, verbose_name='즐겨찾기 여부'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='participant_info',
            field=models.TextField(blank=True, default='', null=True, verbose_name='참가자'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='place_info',
            field=models.TextField(blank=True, default='', null=True, verbose_name='방문 장소'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='transport_info',
            field=models.TextField(blank=True, default='', null=True, verbose_name='교통 정보'),
        ),
    ]
