# Generated by Django 5.0.2 on 2025-05-15 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_input', '0016_schedule_favorite_alter_schedule_participant_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='ai_response',
            field=models.TextField(blank=True, null=True, verbose_name='AI 생성 결과'),
        ),
    ]
