# Generated by Django 5.2 on 2025-05-02 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_input', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='num_people',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='people_composition',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='notes',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='AI 추천 및 메모'),
        ),
    ]
