# Generated by Django 5.2 on 2025-05-02 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_input', '0003_remove_participant_name_participant_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='season_peak',
        ),
    ]
