# Generated by Django 5.2 on 2025-05-02 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_input', '0003_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transport',
            name='arrival',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='departure',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='time',
        ),
        migrations.AddField(
            model_name='schedule',
            name='comments',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='기타 요청사항'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='departure_region',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='출발 지역'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='lodging_request',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='숙소 요청사항'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='num_people',
            field=models.IntegerField(default=1, verbose_name='인원수'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='people_composition',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='사람 구성'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='pet_friendly',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='반려동물 동반 여부'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='purpose',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='여행 목적'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='season_peak',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='성수기 여부'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='type',
            field=models.CharField(max_length=50, verbose_name='교통수단'),
        ),
        migrations.CreateModel(
            name='ImportantFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor', models.CharField(max_length=50, verbose_name='중요 요소')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='important_factors', to='travel_input.schedule')),
            ],
        ),
        migrations.CreateModel(
            name='TravelStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(max_length=50, verbose_name='여행 스타일')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_styles', to='travel_input.schedule')),
            ],
        ),
    ]
