# Generated by Django 5.2 on 2025-05-02 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_input', '0005_participant_age_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='is_family',
        ),
        migrations.AlterField(
            model_name='participant',
            name='age_type',
            field=models.CharField(choices=[('성인', '성인'), ('아동', '아동'), ('가족', '가족')], default='성인', max_length=10, verbose_name='구분'),
        ),
    ]
