# Generated by Django 5.1.6 on 2025-05-02 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel_input", "0006_category_place_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="CultureCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="schedule",
            name="lodging_request",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="숙소 요청 사항"
            ),
        ),
        migrations.AddField(
            model_name="schedule",
            name="people_composition",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="인원 구성"
            ),
        ),
        migrations.AddField(
            model_name="schedule",
            name="pet_friendly",
            field=models.BooleanField(null=True, verbose_name="반려동물 동반"),
        ),
    ]
