# Generated by Django 5.2 on 2025-05-02 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_input', '0006_remove_participant_is_family_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='is_family',
            field=models.BooleanField(default=False, verbose_name='가족 여부'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='age_type',
            field=models.CharField(choices=[('성인', '성인'), ('아동', '아동')], default='성인', max_length=10, verbose_name='구분'),
        ),
    ]
