# Generated by Django 5.1.6 on 2025-05-02 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel_input", "0008_schedule_num_people_schedule_purpose_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="important_factors",
            field=models.CharField(
                blank=True,
                help_text="쉼표로 구분된 값",
                max_length=255,
                verbose_name="중요 요소",
            ),
        ),
        migrations.AddField(
            model_name="schedule",
            name="travel_style",
            field=models.CharField(
                blank=True,
                help_text="쉼표로 구분된 값",
                max_length=255,
                verbose_name="여행 스타일",
            ),
        ),
    ]
