# Generated by Django 5.2 on 2025-05-02 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_input', '0008_alter_importantfactor_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='age',
        ),
        migrations.AddField(
            model_name='participant',
            name='num_people',
            field=models.IntegerField(default=1, verbose_name='인원수'),
        ),
    ]
