# Generated by Django 5.2 on 2025-05-02 06:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_input', '0011_participant_age_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={'verbose_name': '참여자', 'verbose_name_plural': '참여자들'},
        ),
        migrations.AlterField(
            model_name='participant',
            name='age_range',
            field=models.CharField(choices=[('0-2세', '0-2세'), ('3-7세', '3-7세'), ('8-13세', '8-13세'), ('14-19세', '14-19세'), ('20대', '20대'), ('30대', '30대'), ('40대', '40대'), ('50대', '50대'), ('60대', '60대'), ('70대 이상', '70대 이상')], max_length=20, verbose_name='연령대'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='age_type',
            field=models.CharField(choices=[('성인', '성인'), ('청소년', '청소년'), ('아동', '아동'), ('영유아', '영유아')], max_length=10, verbose_name='구분'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='gender',
            field=models.CharField(choices=[('남자', '남자'), ('여자', '여자')], max_length=10, verbose_name='성별'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='is_elderly',
            field=models.BooleanField(default=False, help_text='65세 이상인 경우 체크', verbose_name='노인 여부'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='num_people',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='인원수'),
        ),
    ]
