# Generated by Django 5.0.2 on 2025-05-13 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_input', '0013_remove_budget_schedule_delete_city_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='도시명')),
                ('slug', models.SlugField(unique=True, verbose_name='슬러그')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('order', models.IntegerField(default=0, verbose_name='정렬 순서')),
            ],
            options={
                'verbose_name': '도시',
                'verbose_name_plural': '도시',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TravelOptionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='schedule',
            name='age_group',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='연령대'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='group_type',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='여행 동행 형태'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='language_support',
            field=models.BooleanField(default=False, verbose_name='언어 지원 필요'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='meal_preference',
            field=models.TextField(blank=True, default='', null=True, verbose_name='음식 선호'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='mobility_needs',
            field=models.TextField(blank=True, default='', null=True, verbose_name='이동 관련 요구'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='preferred_activities',
            field=models.TextField(blank=True, default='', null=True, verbose_name='선호 활동'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='repeat_visitor',
            field=models.BooleanField(default=False, verbose_name='재방문 여부'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='season',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='희망 계절'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='transport_info',
            field=models.TextField(blank=True, default='', help_text='교통편, 출발지, 도착지, 시간을 입력하세요', null=True, verbose_name='교통 정보'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='travel_insurance',
            field=models.BooleanField(default=False, verbose_name='여행자 보험 가입'),
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='travel_input.schedule')),
            ],
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupTravel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='그룹명')),
                ('description', models.TextField(verbose_name='그룹 설명')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_groups', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='joined_groups', through='travel_input.GroupMember', to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_travels', to='travel_input.schedule')),
            ],
        ),
        migrations.CreateModel(
            name='GroupMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='travel_input.grouptravel')),
            ],
        ),
        migrations.AddField(
            model_name='groupmember',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_input.grouptravel'),
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='travel_input.schedule')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('visit_date', models.DateField()),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel_input.category', verbose_name='카테고리')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='travel_input.schedule')),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('departure', models.CharField(max_length=100)),
                ('arrival', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transports', to='travel_input.schedule')),
            ],
        ),
        migrations.CreateModel(
            name='TravelOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='travel_input.traveloptioncategory')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='groupmember',
            unique_together={('group', 'user')},
        ),
    ]
