# Generated by Django 5.0.2 on 2025-05-15 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_input', '0017_schedule_ai_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='ai_feedback_response',
            field=models.TextField(blank=True, null=True, verbose_name='AI 개선 제안'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='user_feedback',
            field=models.TextField(blank=True, null=True, verbose_name='사용자 피드백'),
        ),
    ]
