# Generated by Django 5.0.2 on 2025-05-16 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_input', '0018_schedule_ai_feedback_response_schedule_user_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportantFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TravelPurpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TravelStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='city',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='활성화 유무'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='ai_feedback_response',
            field=models.TextField(blank=True, null=True, verbose_name='AI 개전 제안'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='favorite',
            field=models.BooleanField(default=False, verbose_name='즐겨찾기 유무'),
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='important_factors',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='repeat_visitor',
            field=models.BooleanField(default=False, verbose_name='재방문 유무'),
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='travel_purpose',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='travel_style',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='user_feedback',
            field=models.TextField(blank=True, null=True, verbose_name='사용자 피드립'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='important_factors',
            field=models.ManyToManyField(blank=True, to='travel_input.importantfactor', verbose_name='중요 요소'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='travel_purpose',
            field=models.ManyToManyField(blank=True, to='travel_input.travelpurpose', verbose_name='여행 목적'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='travel_style',
            field=models.ManyToManyField(blank=True, to='travel_input.travelstyle', verbose_name='여행 스타일'),
        ),
    ]
