# Generated by Django 5.1.6 on 2025-05-20 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PetProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("animal_type", models.CharField(max_length=50)),
                ("personality", models.CharField(max_length=100)),
            ],
        ),
    ]
