# Generated by Django 5.2.1 on 2025-05-12 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_input', '0011_schedule_age_group_schedule_event_interest_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='country',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='description',
        ),
        migrations.AlterField(
            model_name='destination',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='여행지명'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel_input.destination', verbose_name='여행지'),
        ),
    ]
